"""session preview and mode

Revision ID: 8e05df682aa8
Revises: e1a2b3c4d5e6
Create Date: 2026-09-20 16:37:13.605925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e05df682aa8'
down_revision: Union[str, None] = 'e1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('preview', sa.String(length=160), nullable=True))
    op.add_column('sessions', sa.Column('mode', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'mode')
    op.drop_column('sessions', 'preview')
    # ### end Alembic commands ###
